const data = {
  products: [
    {
      name: 'Iphone 13',
      slug: 'iphone-13',
      category: 'Mobile',
      image: '/images/phone1.png',
      price: 1200,
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: 'Le meilleur mobile',
    },
    {
      name: 'Avions',
      slug: 'avions',
      category: 'Jouet',
      image: '/images/jouet1.jpg',
      price: 15,
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: 'Le meilleur avion',
    },
    {
      name: 'One plus',
      slug: 'one-plus',
      category: 'Mobile',
      image: '/images/phone2.png',
      price: 900,
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: 'Le meilleur mobile',
    },
    {
      name: 'Ceinture',
      slug: 'ceinture',
      category: 'Jouet',
      image: '/images/jouet2.jpg',
      price: 20,
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: 'Le meilleur ceinture',
    },
    {
      name: 'Xiaomi',
      slug: 'xiaomi',
      category: 'Mobile',
      image: '/images/phone3.png',
      price: 300,
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: 'Le meilleur mobile',
    },
    {
      name: 'Bonnet',
      slug: 'bonnet',
      category: 'Jouet',
      image: '/images/jouet3.jpg',
      price: 25,
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: 'ca donne chaud!',
    },
  ],
};
export default data;
